apiVersion: v1
kind: Pod
metadata:
  name: shinyproxy
  labels:
    ci: shinyproxy-build
spec:
  containers:
    - name: shinyproxy-build
      image: public.ecr.aws/docker/library/maven:3-eclipse-temurin-17-focal
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "4Gi"
          cpu: "2"
