apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: shinyproxy-build
spec:
  volumes:
    - name: docker-socket
      emptyDir: { }
    - name: tmp
      emptyDir: { }
  containers:
    - name: shinyproxy-build
      image: public.ecr.aws/docker/library/maven:3-eclipse-temurin-21-jammy
      securityContext:
        runAsUser: 1000
        runAsGroup: 2375
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker/docker.sock
      volumeMounts:
        - mountPath: /var/run/docker
          name: docker-socket
        - mountPath: /tmp/
          name: tmp
      resources:
       requests:
         memory: "4Gi"
         cpu: "2"
       limits:
         memory: "4Gi"
         cpu: "2"
    - name: docker
      image: public.ecr.aws/docker/library/docker:dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker/docker.sock
      volumeMounts:
        - mountPath: /var/run/docker
          name: docker-socket
        - mountPath: /tmp/
          name: tmp
      resources:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "4Gi"
          cpu: "2"
