#!/bin/bash

if [ -d /etc/init ];
then
  cp -u /opt/shinyproxy/shinyproxy.conf /etc/init/shinyproxy.conf
fi

if [ -d /run/systemd/system ];
then
  cp -u /opt/shinyproxy/shinyproxy.service /etc/systemd/system/shinyproxy.service
  systemctl daemon-reload   
fi

# copy default configuration file
mkdir -p /etc/shinyproxy
if [ ! -e /etc/shinyproxy/application.yml ];
then
  cp /opt/shinyproxy/application-demo.yml /etc/shinyproxy/application.yml
  echo demo configuration file is created at /etc/shinyproxy/application.yml
else
  echo using configuration file /etc/shinyproxy/application.yml
fi

TEST=$(ps auxwww | grep /opt/shinyproxy | grep -c -v grep)
if [ $TEST -ne 0 ];
then
  echo shinyproxy is already running, restarting 
  service shinyproxy restart
  exit 0
else
  echo No shinyproxy running, trying to start one...
  
  service shinyproxy start
  if [ -d /run/systemd/system ];
  then
    systemctl enable shinyproxy.service
  fi

  sleep 1
  TEST=$(ps auxwww | grep /opt/shinyproxy | grep -c -v grep)
  if [ $TEST -ne 0 ];
  then
    echo shinyproxy start-up succeeded!
    exit 0
  else
    echo shinyproxy start-up failed! Please start manually with \`service shinyproxy start\`
    exit 1
  fi
fi
